### PR TITLE
Yet more feedback re: hacking minigame incorporated

### PR DESCRIPTION
**Pull request by PeteTimesSix**
Surely. Surely now it's good enough.

### CODE REVIEW

**Comment by PeteTimesSix** [comment]
One more thing I thought of. Keeping the SEND and CLEAR buttons around even if there's no current command, so that the other buttons don't jump around when adding parameters.

**Comment by PeteTimesSix** [comment]
Check out Hacknet sometime. Its my favorite take on the idea :]

**Comment by Alexofp** [comment]
Aww, someone beat me to it x3

**Comment by Alexofp** [comment]
oh? I was literally gonna go through the pull requests tommorrow x3

**Comment by dogboi1120** [comment]
i think we need more bodytypes like taur bird etc

**Pull request closed without merging**
