### PR TITLE
One-handed play support for the cage unlock minigame

### PR DESCRIPTION
**Pull request by PeteTimesSix**
All that work on the mod, and of all the things this one minigame I threw together in an hour continues to be what causes trouble. Here's one last modification to make it not require typing anything and make the hints yet more blatant.

...rats, I was hoping Id manage to sneak this in before the bugfix release.

### CODE REVIEW

**Comment by PeteTimesSix** [comment]
Added a few more smol changes.

**Comment by Alexofp** [comment]
Some people complain that they can't figure out how to take off the hypnovisor when they're hypnotized. I understand that it might be the point of it but people still complain x3

**Comment by Alexofp** [comment]
Lemme know if I can merge

**Comment by Alexofp** [comment]
Silence means yes, let's goooo

**Comment by PeteTimesSix** [comment]
Right, sorry. Yeah, hopefully its all good :]

**Pull request merged**
